/**
 * ============================================================
 *  form.js — All order form logic & submission
 * ============================================================
 *  Handles: quantity stepper, wilaya/commune dropdowns,
 *  delivery type selection, order summary calc,
 *  form validation, and Google Sheets submission.
 * ============================================================
 *  Do NOT edit this file for product changes.
 *  To change delivery prices: edit config/wilayas.js
 *  To change Google Sheets URL: edit config/product.js
 * ============================================================
 */

// ── Facebook Pixel helper ─────────────────────────────────────
// Safe wrapper — does nothing if Pixel wasn't loaded
function pixelTrack(event, params) {
  if (typeof fbq === 'function') {
    fbq('track', event, params);
  }
}

// ── Helpers ──────────────────────────────────────────────────

function getDeliveryType() {
  const r = document.querySelector('input[name="deliveryType"]:checked');
  return r ? r.value : null;
}

function getDeliveryCost() {
  const wid = document.getElementById("wilaya").value;
  const type = getDeliveryType();
  if (!wid || !WILAYAS[wid] || !type) return 0;
  return type === "1" ? WILAYAS[wid].bureauCost : WILAYAS[wid].homeCost;
}

// ── Offer selection ───────────────────────────────────────────

function selectOffer(index) {
  const offer = PRODUCT.offers && PRODUCT.offers[index];
  if (!offer) return;
  const input = document.getElementById("quantity");
  input.value = offer.quantity;
  // Trigger updateSummary which will also handle card highlighting
  updateSummary();
}

// ── Order summary ─────────────────────────────────────────────

function updateSummary() {
  const qty = parseInt(document.getElementById("quantity").value) || 1;

  // Bundle logic: find matching offer or fallback to base price * qty
  const matchingOffer =
    PRODUCT.offers && PRODUCT.offers.find((o) => o.quantity === qty);
  const prod = matchingOffer ? matchingOffer.price : PRODUCT.price * qty;

  // Sync offer cards UI (highlight card if current qty matches)
  document.querySelectorAll(".offer-card").forEach((card) => {
    const idx = parseInt(card.getAttribute("data-index"));
    const offer = PRODUCT.offers && PRODUCT.offers[idx];
    if (offer) {
      card.classList.toggle("is-selected", offer.quantity === qty);
    }
  });

  const del = getDeliveryCost();
  const wid = document.getElementById("wilaya").value;
  const total = prod + (wid && getDeliveryType() ? del : 0);

  document.getElementById("calc-product").textContent =
    prod.toLocaleString("ar-DZ") + " " + PRODUCT.currency;
  document.getElementById("calc-qty").textContent = "× " + qty;
  document.getElementById("calc-delivery").textContent = !wid
    ? "اختر الولاية"
    : !getDeliveryType()
      ? "اختر طريقة التوصيل"
      : del.toLocaleString("ar-DZ") + " " + PRODUCT.currency;
  document.getElementById("calc-total").textContent =
    (wid && getDeliveryType() ? total : prod).toLocaleString("ar-DZ") +
    " " +
    PRODUCT.currency;
}

// ── Quantity stepper ──────────────────────────────────────────

function changeQty(delta) {
  const input = document.getElementById("quantity");
  const next = Math.max(1, Math.min(99, (parseInt(input.value) || 1) + delta));
  input.value = next;
  document.getElementById("qty-minus").disabled = next <= 1;
  updateSummary();
}

// ── Wilaya → commune cascade ──────────────────────────────────

function onWilayaChange() {
  const wid = document.getElementById("wilaya").value;
  const communeEl = document.getElementById("commune");
  const costBureau = document.getElementById("cost-bureau");
  const costHome = document.getElementById("cost-home");

  communeEl.innerHTML =
    '<option value="" disabled selected>اختر بلديتك</option>';

  if (wid && WILAYAS[wid]) {
    communeEl.disabled = false;
    const communes = Array.isArray(WILAYAS[wid].communes)
      ? WILAYAS[wid].communes
      : [];
    communes.forEach((c) => {
      const opt = document.createElement("option");
      opt.value = c;
      opt.textContent = c;
      communeEl.appendChild(opt);
    });
    costBureau.textContent =
      WILAYAS[wid].bureauCost.toLocaleString("ar-DZ") + " " + PRODUCT.currency;
    costHome.textContent =
      WILAYAS[wid].homeCost.toLocaleString("ar-DZ") + " " + PRODUCT.currency;
  } else {
    communeEl.disabled = true;
    costBureau.textContent = "—";
    costHome.textContent = "—";
  }

  updateSummary();
}

// ── Validation ────────────────────────────────────────────────

function showError(fieldId, errId, hasError) {
  const f = document.getElementById(fieldId);
  const e = document.getElementById(errId);
  if (f) f.classList.toggle("error", hasError);
  if (e) e.classList.toggle("show", hasError);
}

function validateForm() {
  const name = document.getElementById("name").value.trim();
  const phone = document.getElementById("phone").value.trim();
  const wilaya = document.getElementById("wilaya").value;
  const commune = document.getElementById("commune").value;
  const delType = getDeliveryType();
  let ok = true;

  const nameOk = name.length >= 3;
  const phoneOk = /^(05|06|07)\d{8}$/.test(phone);

  showError("name", "name-err", !nameOk);
  showError("phone", "phone-err", !phoneOk);
  showError("wilaya", "wilaya-err", !wilaya);
  showError("commune", "commune-err", !commune);

  const delErr = document.getElementById("delivery-err");
  if (delErr) delErr.classList.toggle("show", !delType);

  if (!nameOk || !phoneOk || !wilaya || !commune || !delType) {
    ok = false;
  }
  return ok;
}

// ── Submit to Google Sheets ───────────────────────────────────

function submitForm() {
  // ── FB Pixel: InitiateCheckout (fires on every submit click) ─
  pixelTrack('InitiateCheckout', {
    content_name: PRODUCT.name,
    content_type: 'product',
    value: PRODUCT.price,
    currency: 'DZD',
    num_items: parseInt(document.getElementById('quantity').value) || 1,
  });

  if (!validateForm()) {
    document
      .querySelector(".error")
      ?.scrollIntoView({ behavior: "smooth", block: "center" });
    return;
  }

  const btn = document.getElementById("submit-btn");
  btn.innerHTML = "⏳ جاري الإرسال...";
  btn.disabled = true;

  const wilayaEl = document.getElementById("wilaya");
  const fd = new FormData();
  fd.append("date", new Date().toLocaleString("ar-DZ"));
  fd.append("name", document.getElementById("name").value.trim());
  fd.append("phone", document.getElementById("phone").value.trim());
  fd.append("wilaya", wilayaEl.options[wilayaEl.selectedIndex].text);
  fd.append("commune", document.getElementById("commune").value);
  fd.append("product", PRODUCT.name);

  fd.append("quantity", document.getElementById("quantity").value);
  fd.append("delivery", getDeliveryType() === "1" ? "مكتب" : "منزل");
  fd.append("total", document.getElementById("calc-total").textContent);

  // Debug: Log all FormData fields
  console.log("=== FormData Being Sent ===");
  for (let [key, value] of fd.entries()) {
    console.log(`${key}: ${value}`);
  }
  console.log("===========================");

  const urlEncodedData = new URLSearchParams(fd);
  fetch(PRODUCT.googleScriptURL, {
    method: "POST",
    body: urlEncodedData,
    mode: "no-cors",
  })
    .then(() => {
      // ── FB Pixel: Purchase (fires only on confirmed order) ───
      pixelTrack('Purchase', {
        content_name: PRODUCT.name,
        content_type: 'product',
        content_ids: [PRODUCT.name],
        value: parseFloat(
          document.getElementById('calc-total').textContent.replace(/[^\d.]/g, '')
        ) || PRODUCT.price,
        currency: 'DZD',
        num_items: parseInt(document.getElementById('quantity').value) || 1,
      });
      document.getElementById("success-overlay").classList.add("active");
      resetForm();
    })
    .catch(() => {
      alert("حدث خطأ في الاتصال. يرجى المحاولة مرة أخرى.");
    })
    .finally(() => {
      btn.innerHTML = renderSubmitBtnContent();
      btn.disabled = false;
    });
}

function resetForm() {
  ["name", "phone"].forEach((id) => (document.getElementById(id).value = ""));
  document.getElementById("quantity").value = 1;
  document.getElementById("wilaya").value = "";
  document.getElementById("commune").innerHTML =
    '<option value="" disabled selected>اختر الولاية أولاً</option>';
  document.getElementById("commune").disabled = true;
  document
    .querySelectorAll('input[name="deliveryType"]')
    .forEach((r) => (r.checked = false));

  updateSummary();
}

function renderSubmitBtnContent() {
  return `<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2.5" width="20" height="20">
    <path d="M20 12V22H4V12"/><path d="M22 7H2v5h20V7z"/><path d="M12 22V7"/>
  </svg> أتمم الطلب الآن`;
}

function closeSuccess() {
  document.getElementById("success-overlay").classList.remove("active");
}

// ── Event listeners ───────────────────────────────────────────

document.addEventListener("DOMContentLoaded", async function () {
  if (typeof WILAYAS_READY !== "undefined" && WILAYAS_READY?.then) {
    await WILAYAS_READY;
  }
  document.getElementById("wilaya").addEventListener("change", onWilayaChange);
  document.querySelectorAll('input[name="deliveryType"]').forEach((r) => {
    r.addEventListener("change", updateSummary);
  });
  updateSummary();

  // ── FB Pixel: ViewContent (fires when product page is rendered) ──
  pixelTrack('ViewContent', {
    content_name: PRODUCT.name,
    content_type: 'product',
    content_ids: [PRODUCT.name],
    value: PRODUCT.price,
    currency: 'DZD',
  });
});
