/**
 * ============================================================
 *  render.js — Builds the page HTML from PRODUCT + STORE config
 * ============================================================
 *  Do NOT edit this file unless you want to change the layout.
 *  To change content: edit config/product.js or config/store.js
 * ============================================================
 */

/* ── SVG icon library ── */
const ICONS = {
  shield: `<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><path d="M12 22s8-4 8-10V5l-8-3-8 3v7c0 6 8 10 8 10z"/></svg>`,
  card: `<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><rect x="1" y="4" width="22" height="16" rx="2"/><line x1="1" y1="10" x2="23" y2="10"/></svg>`,
  return: `<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><polyline points="1 4 1 10 7 10"/><path d="M3.51 15a9 9 0 1 0 .49-3.5"/></svg>`,
  cash: `<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><rect x="1" y="4" width="22" height="16" rx="2"/><line x1="1" y1="10" x2="23" y2="10"/></svg>`,
  check: `<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2.5"><path d="M20 6L9 17l-5-5"/></svg>`,
  bag: `<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2.5"><path d="M20 12V22H4V12"/><path d="M22 7H2v5h20V7z"/><path d="M12 22V7"/></svg>`,
};

/* ── Render navbar ── */
function renderNavbar() {
  const logoHTML = STORE.logoImage
    ? `<img src="${STORE.logoImage}" alt="${STORE.logoAlt}" class="logo-img" onerror="this.style.display='none';document.getElementById('logo-text-fallback').style.display='block'">`
    : "";

  const navTrust =
    STORE.navTrust && STORE.navTrust.length > 0
      ? STORE.navTrust
          .map(
            (b) =>
              `<span class="trust-badge">${ICONS[b.icon] || ""} ${b.label}</span>`,
          )
          .join("")
      : "";

  document.getElementById("navbar").innerHTML = `
    <div class="logo-area">
      ${logoHTML}
      <div id="logo-text-fallback" style="display:${STORE.logoImage ? "none" : "block"}">
        <span class="logo-text">${STORE.logoText}</span>
        <span class="logo-tagline">${STORE.logoTagline}</span>
      </div>
    </div>
    <div class="nav-actions">
      <button
        type="button"
        class="hamburger"
        id="nav-hamburger"
        aria-label="القائمة"
        aria-pressed="false"
        title="القائمة"
      >
        <span class="hamburger-bars" aria-hidden="true">
          <span class="hamburger-bar"></span>
          <span class="hamburger-bar"></span>
          <span class="hamburger-bar"></span>
        </span>
      </button>
      <div class="nav-trust">${navTrust}</div>
    </div>
  `;

  const btn = document.getElementById("nav-hamburger");
  if (btn) {
    btn.addEventListener("click", () => {
      const next = btn.getAttribute("aria-pressed") !== "true";
      btn.setAttribute("aria-pressed", String(next));
      btn.classList.toggle("is-active", next);
    });
  }
}

/* ── Render promo banner ── */
function renderBanner() {
  const el = document.getElementById("hero-banner");
  if (!STORE.promoBanner || STORE.promoBanner.length === 0) {
    el.style.display = "none";
    return;
  }
  el.innerHTML = STORE.promoBanner.join(" <span>|</span> ");
}

/* ── Render product info ── */
function renderProduct() {
  // Images (supports PRODUCT.images[] or legacy PRODUCT.image)
  const images =
    Array.isArray(PRODUCT.images) && PRODUCT.images.length
      ? PRODUCT.images
      : PRODUCT.image
        ? [PRODUCT.image]
        : [];

  const imagesContainer = document.getElementById("product-images-container");
  const singleImageEl = document.getElementById("product-image");

  console.log("[renderProduct] images:", images);

  if (imagesContainer) {
    imagesContainer.innerHTML = "";
    images.forEach((imgPath, index) => {
      const img = document.createElement("img");
      img.className = "product-image";
      img.loading = "lazy";
      img.alt = `${PRODUCT.imageAlt} ${index + 1}`;
      img.src = imgPath;
      img.onerror = () => {
        console.warn("[renderProduct] failed to load image:", imgPath);
      };
      imagesContainer.appendChild(img);
    });

    // Manage carousel dots
    const dotsContainer = document.getElementById("carousel-dots");
    if (dotsContainer) {
      dotsContainer.innerHTML = "";
      if (images.length > 1) {
        images.forEach((_, i) => {
          const dot = document.createElement("div");
          dot.className = `carousel-dot ${i === 0 ? "is-active" : ""}`;
          dotsContainer.appendChild(dot);
        });

        imagesContainer.addEventListener("scroll", () => {
          // Calculate the active index based on scroll position
          const scrollPos = Math.abs(imagesContainer.scrollLeft);
          const itemWidth = imagesContainer.clientWidth;
          const activeIndex = Math.round(scrollPos / itemWidth);

          const dots = dotsContainer.querySelectorAll(".carousel-dot");
          dots.forEach((dot, index) => {
            dot.classList.toggle("is-active", index === activeIndex);
          });
        });
      }
    }
  } else if (singleImageEl && images[0]) {
    singleImageEl.src = images[0];
    singleImageEl.alt = PRODUCT.imageAlt;
    singleImageEl.onerror = () => {
      console.warn("[renderProduct] failed to load image:", images[0]);
    };
  }

  // Badge
  const badgeEl = document.getElementById("product-badge");
  if (PRODUCT.badge) {
    badgeEl.textContent = PRODUCT.badge;
    badgeEl.style.display = "block";
  } else {
    badgeEl.style.display = "none";
  }

  // Category & title
  document.getElementById("product-category").textContent = PRODUCT.category;
  document.getElementById("product-title").textContent = PRODUCT.name;

  // Stars
  document.getElementById("stars").textContent =
    "★".repeat(PRODUCT.stars) + "☆".repeat(5 - PRODUCT.stars);
  document.getElementById("rating-count").textContent =
    `(${PRODUCT.reviewCount} تقييم) · أكثر من ${PRODUCT.orderCount} طلب`;

  // Price
  document.getElementById("price-main").textContent =
    PRODUCT.price.toLocaleString("ar-DZ");
  document.getElementById("price-currency").textContent = PRODUCT.currency;

  const oldPriceEl = document.getElementById("price-old");
  const savingEl = document.getElementById("price-saving");
  if (savingEl) savingEl.style.display = "none";

  if (PRODUCT.oldPrice) {
    oldPriceEl.textContent = `${PRODUCT.oldPrice.toLocaleString("ar-DZ")} ${PRODUCT.currency}`;
    oldPriceEl.style.display = "";
  } else {
    oldPriceEl.style.display = "none";
  }

  // Description
  document.getElementById("product-desc").textContent = PRODUCT.description;

  // Features
  document.getElementById("features").innerHTML = PRODUCT.features
    .map(
      (f) => `
    <span class="feature-pill">${ICONS.check} ${f}</span>
  `,
    )
    .join("");
}

/* ── Render wilaya options ── */
function renderWilayas() {
  const el = document.getElementById("wilaya");
  const opts = Object.entries(WILAYAS)
    .sort(([a], [b]) => parseInt(a) - parseInt(b))
    .map(([id, w]) => `<option value="${id}">${id} - ${w.name}</option>`)
    .join("");
  el.innerHTML =
    `<option value="" disabled selected>اختر ولايتك</option>` + opts;
}

/* ── Render trust strip ── */
function renderTrustStrip() {
  const trustEl = document.getElementById("trust-strip");
  if (!trustEl) return;
  trustEl.innerHTML = STORE.trustStrip
    .map(
      (t) => `
    <div class="trust-item">${ICONS[t.icon] || ""} ${t.label}</div>
  `,
    )
    .join("");
}

/* ── Boot ── */
document.addEventListener("DOMContentLoaded", async () => {
  if (typeof WILAYAS_READY?.then === "function") {
    await WILAYAS_READY;
  }
  renderNavbar();
  renderBanner();
  renderProduct();
  renderWilayas();
  renderTrustStrip();
});
